#!/usr/bin/env bash
# Generates a vector with the BUILDING BLOCK'S OWN CODE, without touching the building-blocks repo:
# extracts origin/main (git archive) into a temp dir, links the repo's node_modules and runs it with bun.
#   scripts/bb-vector.sh static vectors/vectors.json
#   scripts/bb-vector.sh fresh  /tmp/delivery.json
set -euo pipefail
MODE="${1:?static|fresh}"; OUT="$(realpath -m "${2:?output file}")"
BB_REPO="${BB_REPO:-$HOME/Projects/building-blocks-v2}"
BB_REF="${BB_REF:-origin/main}"
HERE="$(cd "$(dirname "$0")" && pwd)"
WORK="${BB_EXTRACT_DIR:-}"
if [ -z "$WORK" ]; then WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT; fi
if [ ! -f "$WORK/.extracted" ]; then
  git -C "$BB_REPO" archive "$BB_REF" src tsconfig.json package.json | tar -x -C "$WORK"
  ln -sfn "$BB_REPO/node_modules" "$WORK/node_modules"
  git -C "$BB_REPO" rev-parse --short "$BB_REF" > "$WORK/.extracted"
fi
cp "$HERE/gen-vectors.bb.ts" "$WORK/gen-vectors.ts"
(cd "$WORK" && bun run gen-vectors.ts "$MODE" "$OUT" >/dev/null)
echo "$MODE vector generated by building-blocks $(cat "$WORK/.extracted") at $OUT"
